# Make Overwatch run borderless fullscreen
windowrulev2 = fullscreen, class:^(steam_app_2357570)$

# Make Steam behave like a normal window
windowrulev2 = float, class:^(steam)$, title:^(Steam)
windowrulev2 = tile, class:^(steam)$
windowrulev2 = size 1200 800, class:^(steam)$
# Kitty translucent
#windowrulev2 = opacity 0.70 0.70,class:^(kitty)$


